# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e84f4a7fecd1e8c9c05791a35c0336d4"
name = "Argora - Cart Recovery"
application_url = "https://argora.ai"
embedded = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "https://argora.ai/api/webhooks/orders"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://argora.ai/api/webhooks/uninstall"

  [[webhooks.subscriptions]]
  uri = "https://argora.ai/api/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://argora.ai/api/auth/shopify/callback" ]

[pos]
embedded = false
