# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "08fa8bc27e0e3ac857912c7e7ee289d0"
name = "Adwyse"
application_url = "https://adwyse.ca"
embedded = true

[webhooks]
api_version = "2024-10"
# Webhooks are registered via code during OAuth callback

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders"
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://adwyse.ca/api/auth/shopify/callback",
  "https://adwyse.ca/api/billing/callback"
]
